### ISSUE TITLE
Crystal OS virtual disk 

### ISSUE THREAD

**Issue by teleguest** [Xatom-Team/Zacisza-Archive#3]
link to mega : https://mega.nz/#!GtkFyTTK

password : SHprEScu_wZTFK2JD6wgSvSJDCfo0QWeP3DRa10mMd0

**Comment by Nambona2115** [comment]
Zamiast zasyfiać githuba jakimś beznadziejnym distro, udawając "pro uber mega linuksiarza" pouczył byś się angielskiego (patrząc na kod źródłowy "Pumpkin OS" To woła o pomstę do nieba) Dopiero potem pomyśl aby się dokształcić, bo pewnie nawet nie masz pojęcia co wpisywać w terminalu.

**Comment by LamaPolska** [comment]
Specjalnie się zarejestrowałeś te kilka godzin temu żeby napisać
